### ISSUE TITLE
Add support for CSS-only zebra striping

### ISSUE THREAD

**Issue by flack** [openpsa/grid.js#16]
Currently, it is not possible to implement CSS-only zebra striping, because hidden rows (e.g. collapsed groups or collapsed child levels) have the same classes as visible ones. So if you have a CSS rule like

```css
.ui-jqgrid-btable tr.jqgrow:nth-child(2n+1)
{
    background-color: gray
}
``` 

it will only work in simple cases, but it will produce wrong results if some of the rows are hidden. 

So I would propose adding a class like `jqrow-visible` to all visible rows, then we could write

```css
.ui-jqgrid-btable tr.jqgrow-visible:odd
{
    background-color: gray
}
``` 

without needing `altrows` and `altclass` config options
